spring:
    profiles:
        active: prod
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 9999
my:
    class:
        size: 10
        name: first-alp-class
        description: My Class name is ${my.class.name}
        servers:
            - server1.com
            - server2.com
